services:
  document_service:
    build:
      context: ./document_service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./document_service/public:/usr/src/app/public
      - ./document_service/uploads:/usr/src/app/uploads
      - ./document_service/pdf:/usr/src/app/pdf
    environment:
      - NODE_ENV=production
      - TRANSLATE_URL=http://translate_ai:8000/

  translate_ai:
    build:
      context: ./translate_ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./translate_ai:/app
    environment:
      - TRAINING_INTERVAL:3600

  onlyoffice:
    image: onlyoffice/documentserver
    ports:
      - "9000:80"
    environment:
      - JWT_ENABLED=false
    volumes:
      - ./web-apps/apps/common/main/resources/img/:/var/www/onlyoffice/documentserver/web-apps/apps/common/main/resources/img/
      - ./web-apps/apps/documenteditor/main/:/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/